version: 1.0.{build}
image: Visual Studio 2022

build_script:
  - dotnet restore
  - dotnet build --no-restore

test_script:
  - ps: |
      Write-Host "🧪 Testler çalıştırılıyor..."
      try {
          dotnet test "CalculatorAppToLearnCICDPipeline.Tests" --no-build `
              --logger "trx;LogFileName=test_results.trx" `
              --logger "html;LogFileName=test_report.html" `
              --results-directory "$env:APPVEYOR_BUILD_FOLDER\CalculatorAppToLearnCICDPipeline.Tests\TestResults"
      } catch {
          Write-Host "⚠ Testler başarısız oldu, build devam ediyor..."
      }

artifacts:
  - path: CalculatorAppToLearnCICDPipeline.Tests\TestResults\**
    name: TestResults
  - path: CalculatorAppToLearnCICDPipeline\bin\Debug\net8.0\**
    name: BuildDLLs
