version: 1.0.{build}
image: Visual Studio 2022

# Build adımları
build_script:
  - dotnet restore
  - dotnet build --no-restore

# Test adımları
test_script:
  - ps: |
      Write-Host "🧪 Testler çalıştırılıyor..."
      # Testleri çalıştır, başarısız olsa da devam et
      dotnet test "CalculatorAppToLearnCICDPipeline.Tests" --no-build `
        --logger "trx;LogFileName=test_results.trx" `
        --logger "html;LogFileName=test_report.html" `
        --results-directory "CalculatorAppToLearnCICDPipeline.Tests\TestResults" `
        || Write-Host "⚠ Testler başarısız oldu, build devam ediyor..."

# Artifacts: test dosyalarını al
artifacts:
  - path: CalculatorAppToLearnCICDPipeline.Tests\TestResults\**
    name: TestResults
