version: 1.0.{build}

# Visual Studio 2022 image kullanıyoruz
image: Visual Studio 2022

# .NET 8 SDK kurulumu
install:
  # Eğer SDK zaten yüklüyse bu adım atlanır
  - ps: Install-Product dotnet 8.0.100

# AppVeyor varsayılan msbuild çağrılarını devre dışı bırakmak için sadece YAML ile build
# build_script bölümünde dotnet CLI kullanıyoruz
build_script:
  # SDK ve ortam bilgilerini görmek için
  - dotnet --info

  # NuGet paketlerini restore et
  - dotnet restore CalculatorAppToLearnCICDPipeline.sln

  # Ana projeyi ve test projelerini build et
  - dotnet build CalculatorAppToLearnCICDPipeline.sln --no-restore --configuration Release

  # Testleri çalıştır
  - dotnet test CalculatorAppToLearnCICDPipeline.sln --no-build --configuration Release

# Artık AppVeyor UI üzerinden "Visual Studio Solution" build adımı eklemeyin
# Sadece bu YAML dosyasıyla build gerçekleşecek
