version: 1.0.{build}
image: Visual Studio 2022

install:
  - ps: Install-Product dotnet 9.0.306

build_script:
  - dotnet restore
  - dotnet build --no-restore

test_script:
  - dotnet test --no-build --logger "trx;LogFileName=test_results.trx"

artifacts:
  - path: '**\test_results.trx'
    name: TestResults
