version: 1.0.{build}
image: Visual Studio 2022

install:
  - ps: Install-Product dotnet 8.0.100

build_script:
  - dotnet --info            # SDK ve workload’ları kontrol etmek için
  - dotnet restore
  - dotnet build --no-restore
  - dotnet test --no-build
